---
name: Playwright Speedometer Benchmark
author: Didi <didi@green-coding.io>
description: Runs the Speedometer 3.1 benchmark via Playwright in a headless/ headfull Firefox and Chrome browser.

services:
  speedtest:
    image: ribalba/speedometer:4.0.0-alpha

  playwright-runner:
    image: greencoding/gcb_playwright:v21
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode
    command: [ "tail", "-f", "/dev/null" ]   # keep container running

flow:
  - name: Run Speedometer 3.1 Firefox Headless
    container: playwright-runner
    commands:
      - type: console
        command: python3 /tmp/repo/run_speedometer.py --headless --browser firefox --url http://speedtest
        note: Run Speedometer 3.1 benchmark in headless Firefox and output JSON score

  - name: Run Speedometer 3.1 Firefox Headfull
    container: playwright-runner
    commands:
      - type: console
        command: python3 /tmp/repo/run_speedometer.py --headful --browser firefox --url http://speedtest
        note: Run Speedometer 3.1 benchmark in headful Firefox and output JSON score

  - name: Run Speedometer 3.1 Chrome Headless
    container: playwright-runner
    commands:
      - type: console
        command: python3 /tmp/repo/run_speedometer.py --headless --browser chromium --url http://speedtest
        note: Run Speedometer 3.1 benchmark in headless Chrome and output JSON score

  - name: Run Speedometer 3.1 Chrome Headfull
    container: playwright-runner
    commands:
      - type: console
        command: python3 /tmp/repo/run_speedometer.py --headful --browser chromium --url http://speedtest
        note: Run Speedometer 3.1 benchmark in headful Chrome and output JSON score
